name: govulncheck

on:
  push:
    branches:
      - master
    paths:
      - '**/*.go'
      - go.mod
      - go.sum
      - Makefile
      - builder/**
      - command/**
      - config/**
      - configure/**
      - module3rd/**
      - openresty/**
      - util/**
      - '.github/workflows/security.yml'
  pull_request:
    paths:
      - '**/*.go'
      - go.mod
      - go.sum
      - Makefile
      - builder/**
      - command/**
      - config/**
      - configure/**
      - module3rd/**
      - openresty/**
      - util/**
      - '.github/workflows/security.yml'
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    timeout-minutes: 15
    steps:
      - name: Start cicd-sensor
        uses: cicd-sensor/cicd-sensor-action@777ddaafc9ec2e09c9779cdb860e75906adc19c2 # v0.0.34

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: 1.26.4

      - name: Install govulncheck
        run: |
          mkdir -p "$HOME/bin"
          echo "$HOME/bin" >> "$GITHUB_PATH"
          GOBIN="$HOME/bin" go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck
        run: govulncheck ./...
